[build]
builder = "nixpacks"
buildCommand = "composer install --optimize-autoloader --no-dev"

[deploy]
startCommand = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
