[build]
builder = "nixpacks"
buildCommand = "composer install --optimize-autoloader --no-dev"

[deploy]
startCommand = "echo \"PORT is: $PORT\" && php artisan migrate --force && php artisan config:clear && php artisan serve --host=0.0.0.0 --port=$PORT"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[variables]
APP_ENV = "production"
APP_DEBUG = "false"
SESSION_DRIVER = "database"
LOG_CHANNEL = "stderr"
LOG_LEVEL = "error"
CACHE_STORE = "database"
QUEUE_CONNECTION = "database"
